package jframe;

import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class SingUpPage extends javax.swing.JFrame {

    HomePage cadastrando;
    
    /**
     * Creates new form SingUp
     */
    public SingUpPage() {
        initComponents();
    }

    // method to insert values into tb_usuario
    public void inserirDados(){
        String nome = txtNome.getText();
        String email = txtEmail.getText();
        String senha = txtSenha.getText();
        String telefone = txtTelefone.getText();
        
        try{
            Connection con = DBConnection.getConnection();            
            String sql = "insert into tb_usuario(nomeUsuario, emailUsuario, senhaUsuario, telefoneUsuario) values(?,?,?,?)";                        
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, nome);
            pst.setString(2, email);
            pst.setString(3, senha);
            pst.setString(4, telefone);
            
            int updateRowCount = pst.executeUpdate();
            
            if(updateRowCount > 0){
                JOptionPane.showMessageDialog(this, "Dados salvos com sucesso!");
                JOptionPane.showMessageDialog(this, "Bem vindo " + nome);
                cadastrando = new HomePage();
                cadastrando.setVisible(true);
                cadastrando.recebendoEmail(email);
                /*HomePage home = new HomePage();
                home.setVisible(true);*/
                this.dispose();                
            }else{
                JOptionPane.showMessageDialog(this, "Erro no salvamento dos dados!");
            }
            
        }catch (Exception e){
            e.printStackTrace();
        }
    }
    
    // validation
    public boolean validateSignup(){
        String nome = txtNome.getText();
        String email = txtEmail.getText();
        String senha = txtSenha.getText();
        String telefone = txtTelefone.getText();
        
        if (nome.isBlank() || email.isBlank() || senha.isBlank() || telefone.isBlank()){
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos");
            return false;
        } 
        if(!email.matches("^.+@.+\\..+$")){
            JOptionPane.showMessageDialog(this, "Informe um email válido");
            return false;
        }
        if(senha.length()<6 || senha.length()>15){
            JOptionPane.showMessageDialog(this, "A senha deve conter de 6 a 15 caracteres");
            return false;
        }
        if(telefone.length()<=10){
            JOptionPane.showMessageDialog(this, "O telefone (contando DDD) deve ter 11 caracteres");
            return false;
        }
        
        return true;
    }
    
    public boolean checkDuplicatePhone(){
        String telefone = txtTelefone.getText();
        boolean jaCadastrado = false;
        
        try{
            Connection con = DBConnection.getConnection();
            
            // checking the phone
            PreparedStatement pst = con.prepareStatement("select * from tb_usuario where telefoneUsuario = ?");
            pst.setString(1,telefone);
            ResultSet rs = pst.executeQuery();
            jaCadastrado = rs.next();
            
        }catch(Exception e){
            e.printStackTrace();
        }
        return jaCadastrado;
    }
    
    // check duplicates users
    public boolean checkDuplicateEmail(){
        String email = txtEmail.getText();
        boolean jaCadastrado = false;
        
        try{
            Connection con = DBConnection.getConnection();
            
            // checking the email
            PreparedStatement pst = con.prepareStatement("select * from tb_usuario where emailUsuario = ?");
            pst.setString(1,email);
            ResultSet rs = pst.executeQuery();
            jaCadastrado = rs.next();
            
        }catch(Exception e){
            e.printStackTrace();
        }
        return jaCadastrado;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        logoText = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nomeIconLabel = new javax.swing.JLabel();
        fecharLabel = new javax.swing.JLabel();
        subtituloLabel = new javax.swing.JLabel();
        txtNome = new app.bolivia.swing.JCTextField();
        nomeLabel = new javax.swing.JLabel();
        emailIconLabel = new javax.swing.JLabel();
        txtEmail = new app.bolivia.swing.JCTextField();
        loginButtonLabel = new javax.swing.JLabel();
        txtSenha = new app.bolivia.swing.JCTextField();
        senhaIconLabel = new javax.swing.JLabel();
        telefoneLabel = new javax.swing.JLabel();
        txtTelefone = new app.bolivia.swing.JCTextField();
        telefoneIconLabel = new javax.swing.JLabel();
        cadastrarButton = new rojerusan.RSMaterialButtonCircle();
        emailLabel = new javax.swing.JLabel();
        senhaLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoPanel.setBackground(new java.awt.Color(255, 255, 255));
        logoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Java-Logo.png"))); // NOI18N
        logoPanel.add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 580, -1));

        logoText.setBackground(new java.awt.Color(255, 51, 51));
        logoText.setFont(new java.awt.Font("UD Digi Kyokasho NP-R", 0, 48)); // NOI18N
        logoText.setForeground(new java.awt.Color(204, 0, 51));
        logoText.setText("CLOTHES & BOOTS");
        logoPanel.add(logoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        jPanel1.add(logoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 740, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 720));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeIconLabel.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        nomeIconLabel.setForeground(new java.awt.Color(255, 255, 255));
        nomeIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel2.add(nomeIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 60, 60));

        fecharLabel.setFont(new java.awt.Font("Sitka Small", 1, 30)); // NOI18N
        fecharLabel.setForeground(new java.awt.Color(255, 255, 255));
        fecharLabel.setText("X");
        fecharLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fecharLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fecharLabelMouseClicked(evt);
            }
        });
        jPanel2.add(fecharLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 30, 50));

        subtituloLabel.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        subtituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        subtituloLabel.setText("Crie uma nova conta aqui");
        jPanel2.add(subtituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, 20));

        txtNome.setBackground(new java.awt.Color(102, 102, 255));
        txtNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtNome.setPhColor(new java.awt.Color(255, 255, 255));
        txtNome.setPlaceholder("Digite seu nome...");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel2.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 250, 40));

        nomeLabel.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        nomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        nomeLabel.setText("Nome");
        jPanel2.add(nomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 60, 20));

        emailIconLabel.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        emailIconLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Secured_Letter_50px.png"))); // NOI18N
        jPanel2.add(emailIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 60, 80));

        txtEmail.setBackground(new java.awt.Color(102, 102, 255));
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtEmail.setPhColor(new java.awt.Color(255, 255, 255));
        txtEmail.setPlaceholder("Digite seu email...");
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 250, 40));

        loginButtonLabel.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        loginButtonLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginButtonLabel.setText("Já possui uma conta? Clique aqui");
        loginButtonLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonLabelMouseClicked(evt);
            }
        });
        jPanel2.add(loginButtonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 630, 290, 20));

        txtSenha.setBackground(new java.awt.Color(102, 102, 255));
        txtSenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtSenha.setPhColor(new java.awt.Color(255, 255, 255));
        txtSenha.setPlaceholder("Digite sua senha...");
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        jPanel2.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 250, 40));

        senhaIconLabel.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        senhaIconLabel.setForeground(new java.awt.Color(255, 255, 255));
        senhaIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Secure_50px.png"))); // NOI18N
        jPanel2.add(senhaIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 60, 70));

        telefoneLabel.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        telefoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        telefoneLabel.setText("Telefone");
        jPanel2.add(telefoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 80, 20));

        txtTelefone.setBackground(new java.awt.Color(102, 102, 255));
        txtTelefone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtTelefone.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefone.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtTelefone.setPhColor(new java.awt.Color(255, 255, 255));
        txtTelefone.setPlaceholder("Digite seu telefone...");
        txtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefoneFocusLost(evt);
            }
        });
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        jPanel2.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 250, 40));

        telefoneIconLabel.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        telefoneIconLabel.setForeground(new java.awt.Color(255, 255, 255));
        telefoneIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Google_Mobile_50px.png"))); // NOI18N
        jPanel2.add(telefoneIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 60, -1));

        cadastrarButton.setBackground(new java.awt.Color(255, 51, 51));
        cadastrarButton.setText("Cadastrar");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cadastrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 270, 70));

        emailLabel.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email");
        jPanel2.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 60, 20));

        senhaLabel.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        senhaLabel.setForeground(new java.awt.Color(255, 255, 255));
        senhaLabel.setText("Senha");
        jPanel2.add(senhaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 60, 20));

        tituloLabel.setFont(new java.awt.Font("Sitka Small", 1, 25)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setText("Cadastrar");
        jPanel2.add(tituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 480, 720));

        setSize(new java.awt.Dimension(1300, 713));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        if(validateSignup()){
            if(checkDuplicateEmail()){
                JOptionPane.showMessageDialog(this, "Este email já está cadastrado");
            }else{
                if(checkDuplicatePhone()){
                    JOptionPane.showMessageDialog(this, "Este telefone já está cadastrado");
                } else {
                    inserirDados();
                }
            }
        }
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void fecharLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_fecharLabelMouseClicked

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if(checkDuplicateEmail()){
            JOptionPane.showMessageDialog(this, "Este email já está cadastrado");
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneFocusLost
        if(checkDuplicatePhone()){
            JOptionPane.showMessageDialog(this, "Este telefone já está cadastrado");
        }
    }//GEN-LAST:event_txtTelefoneFocusLost

    private void loginButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonLabelMouseClicked
        LoginPage login = new LoginPage();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginButtonLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SingUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SingUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SingUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SingUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splashScreen.SplashScreen(null, true).setVisible(true);
                new SingUpPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonCircle cadastrarButton;
    private javax.swing.JLabel emailIconLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel fecharLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loginButtonLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel logoText;
    private javax.swing.JLabel nomeIconLabel;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JLabel senhaIconLabel;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JLabel subtituloLabel;
    private javax.swing.JLabel telefoneIconLabel;
    private javax.swing.JLabel telefoneLabel;
    private javax.swing.JLabel tituloLabel;
    private app.bolivia.swing.JCTextField txtEmail;
    private app.bolivia.swing.JCTextField txtNome;
    private app.bolivia.swing.JCTextField txtSenha;
    private app.bolivia.swing.JCTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
